version: '3.8'

services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - '5432:5432' #{port in host(myPC)} : {port in container}
      #environment variables, like: db's name,pw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456aA
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:
    #Create container,network,... form docker compose file:
    #-d : deamon/background mode
    #docker compose up -d
    #if u want to start only specified services/container:
    #docker compose up -d dev-database -d
